DIScopeVsTransientVsSingletonSample/Models/ErrorViewModel.cs
using System;

namespace DIScopeVsTransientVsSingletonSample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DIScopeVsTransientVsSingletonSample/Controllers/HomeController.cs
using DIScopeVsTransientVsSingletonSample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DIScopeVsTransientVsSingletonSample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DIScopeVsTransientVsSingletonSample/Controllers/OperationsController.cs
using DIScopeVsTransientVsSingletonSample.Interfaces;
using DIScopeVsTransientVsSingletonSample.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DIScopeVsTransientVsSingletonSample.Controllers
{
    public class OperationsController : Controller
    {
        private readonly OperationService _operationService;
        private readonly IOperationTransient _transientOperation;
        private readonly IOperationScoped _scopedOperation;
        private readonly IOperationSingleton _singletonOperation;
        private readonly IOperationSingletonInstance _singletonInstanceOperation;

        public OperationsController(OperationService operationService,
            IOperationTransient transientOperation,
            IOperationScoped scopedOperation,
            IOperationSingleton singletonOperation,
            IOperationSingletonInstance singletonInstanceOperation)
        {
            _operationService = operationService;
            _transientOperation = transientOperation;
            _scopedOperation = scopedOperation;
            _singletonOperation = singletonOperation;
            _singletonInstanceOperation = singletonInstanceOperation;
        }

        public IActionResult Index()
        {
            // ViewBag contains controller-requested services
            ViewBag.Transient = _transientOperation;
            ViewBag.Scoped = _scopedOperation;
            ViewBag.Singleton = _singletonOperation;
            ViewBag.SingletonInstance = _singletonInstanceOperation;

            // Operation service has its own requested services
            ViewBag.Service = _operationService;
            return View();
        }
    }
}

DIScopeVsTransientVsSingletonSample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DIScopeVsTransientVsSingletonSample/Views/Operations/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string transient = ViewBag.Transient.OperationId.ToString();
    string scope = ViewBag.Scoped.OperationId.ToString();
    string singleton = ViewBag.Singleton.OperationId.ToString();
    string instance = ViewBag.Instance != null ? ViewBag.Instance.OperationId.ToString() : Guid.Empty.ToString();

    string serviceTansientOperation = ViewBag.Service.TransientOperation.OperationId.ToString(); ;
    string serviceScopeOperation = ViewBag.Service.ScopedOperation.OperationId.ToString(); ;
    string serviceSingletonOperation = ViewBag.Service.SingletonOperation.OperationId.ToString(); ;
    string serviceInstanceOperation = ViewBag.Service.SingletonInstanceOperation != null ? ViewBag.Service.SingletonInstanceOperation.OperationId.ToString() : Guid.Empty.ToString();
}

<h1>Singleton / Transient / Scope - Sample</h1>


<h2><b>First Call</b></h2>
<p>Transient: @transient</p>
<p>Scoped: @scope</p>
<p>Singleton: @singleton</p>
<p>Instance: @instance</p>

<hr />
<h2><b>Second Call</b></h2>
<p>Service Transient: @serviceTansientOperation</p>
<p>Service Scoped: @serviceScopeOperation</p>
<p>Service Singleton: @serviceSingletonOperation</p>
<p>Service Instance: @serviceInstanceOperation</p>

DIScopeVsTransientVsSingletonSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DIScopeVsTransientVsSingletonSample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DIScopeVsTransientVsSingletonSample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Operations" asp-action="Index">Zum Beispiel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DIScopeVsTransientVsSingletonSample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>